### ISSUE TITLE
自动放行建议

### ISSUE THREAD

**Issue by wuscloud** [JerryLinLinLin/Huorong-ATP-Rules#22]
这种情况是否应该添加到自动放行规则里。
![image](https://user-images.githubusercontent.com/12063279/209496125-4b19dff6-9f18-400f-8868-cc9038835af9.png)

**Comment by JerryLinLinLin** [comment]
请问导入自动处理规则了吗？如果按照说明导入了auto.json 不应该出现此拦截。
