### ISSUE TITLE
[建议] 增加对WPS的支持规则

### ISSUE THREAD

**Issue by imroxe** [JerryLinLinLin/Huorong-ATP-Rules#25]
- 当前规则对办公套件的支持是微软的office，建议增加个wps的。
- 至于规则功能，和ms差不多吧，对exe和注册表监控。
- *感谢作者的付出！*

---

- English is not well, so, there is nothing.
- *Thank you for your time.*

**Comment by JerryLinLinLin** [comment]
WPS 的附加组件和广告插件会导致规则误报，暂不考虑
